### ISSUE TITLE
Reviewing first pass at CPP in python

### ISSUE THREAD

**Issue by danielmlow** [satvik-dixit/CPP#1]
@satra ,  @satvik-dixit started from the implementation of the cepstrum I had for the UVP paper and computed the CPP from there. He also ran it in Praat to compare and he's getting slightly different results. Perhaps you can give the code a quick look to see if we're missing something. He thinks maybe smoothing. 

Here are some resources in case they're useful:

About CPP:
- Fraile, R., & Godino-Llorente, J. I. (2014). Cepstral peak prominence: A comprehensive analysis. Biomedical Signal Processing and Control, 14, 42-54.
- Murton, O., Hillman, R., & Mehta, D. (2020). Cepstral peak prominence values for clinical voice evaluation. American Journal of Speech-Language Pathology, 29(3), 1596-1607.

Code:
- implementation in matlab https://github.com/covarep/covarep/blob/master/glottalsource/cpp.m

**Comment by satra** [comment]
i can take a look tomorrow. but on a quick look, i would start with the functions already in librosa. there is no need to implement another cepstral extraction (learning is ok, but should switch to a library).

**Comment by danielmlow** [comment]
@satra so Librosa has only a clean implementation of the MFCCs, so perhaps @satvik-dixit uses these Python implementations of the cepstrum (without mel filters and DCT): https://github.com/python-acoustics/python-acoustics/blob/master/acoustics/cepstrum.py

Sees how results change with the different implementations.

And looks through the matlab implementation a bit more (perhaps gets it to run) and compare to Praat and try to copy the smoothing details into Python if needed.

**Comment by danielmlow** [comment]
Satvik used those implementations from the python-acoustics package and has also matched the outputs from the matlab implementation.
